name = "RBFs"
uuid = "9de28636-5028-44ac-b23d-27f9d7b5f036"
authors = ["EIA-FTA"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
